version: '3.7'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/next-app
      - /usr/src/next-app/node_modules
      - /usr/src/next-app/.next
    ports:
      - 3000:3000
